name: ci

on:
  pull_request:
    branches:
      - main
  pull_request_target:
    types:
      - labeled
  merge_group:
    types:
      - checks_requested

jobs:
  fmt:
    if: |
      github.event_name == 'merge_group' ||
      (github.event_name == 'pull_request' && ! github.event.pull_request.head.repo.fork && github.event.pull_request.user.login != 'dependabot[bot]' && ! contains(github.event.pull_request.labels.*.name, 'safe-to-test')) ||
      (github.event_name == 'pull_request_target' && contains(github.event.pull_request.labels.*.name, 'safe-to-test'))
    uses: signoz/primus.workflows/.github/workflows/js-fmt.yaml@main
    secrets: inherit
    with:
      PRIMUS_REF: main
      NODE_VERSION: "24"
      JS_SRC: .
      JS_PKG_MANAGER: pnpm
  lint:
    if: |
      github.event_name == 'merge_group' ||
      (github.event_name == 'pull_request' && ! github.event.pull_request.head.repo.fork && github.event.pull_request.user.login != 'dependabot[bot]' && ! contains(github.event.pull_request.labels.*.name, 'safe-to-test')) ||
      (github.event_name == 'pull_request_target' && contains(github.event.pull_request.labels.*.name, 'safe-to-test'))
    uses: signoz/primus.workflows/.github/workflows/js-lint.yaml@main
    secrets: inherit
    with:
      PRIMUS_REF: main
      NODE_VERSION: "24"
      JS_SRC: .
      JS_PKG_MANAGER: pnpm
