name: release

on:
  push:
    branches:
      - "main"

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  release:
    permissions:
      contents: write
      id-token: write
      pull-requests: write
      id-token: write
    uses: signoz/primus.workflows/.github/workflows/js-release.yaml@js-release
    secrets: inherit
    with:
      PRIMUS_REF: git
